export default {
  minerals: [
    'Copper_Ore',
    'Cave_Sulfur',
    'Diamond',
    'Gas_Pod',
    'Gold',
    'Gold',
    'Kyanite',
    'Lead',
    'Lithium',
    'Magnetite',
    'Metal_Salvage',
    'Nickel_Ore',
    'Quartz',
    'Ruby',
    'Salt_Deposit',
    'Alien_Feces',
    'Silver_Ore',
    'Stalker_Teeth',
    'Crystalline_Sulfur',
    'Uraninite_Crystal',
  ],
  corals: [
    'Coral_Tube_Sample',
    'Fungal_Sample',
    'Brain_Coral_Sample',
    'Table_Coral_Sample',
  ],
  flora: [
    'Acid_Mushroom',
    'Deep_Shroom',
  ],
};
